server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  security:
    enabled: true
  mvc:
    validation:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://39.98.41.126:3306/pedestal?useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_QGPASSWORD}
  redis:
    host: 39.98.41.126
    port: 6379
    password: ${REDIS_PASSWORD}
    lettuce:
      pool:
        max-active: 12
        max-idle: 11
        time-between-eviction-runs: 10s
      shutdown-timeout: 0
    database: 1
  mail:
    host: smtp.qq.com
    username: 2824687171@qq.com
    password: wfwiwtwpqdjsdcfi
    default-encoding: UTF-8

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mqtt:
  host: tcp://broker.emqx.io:1883
  username: test
  password: test
  qos: 2
  clientId: mqttx_bb12qeweqweqweqw231213212 #ClientId_local必须唯一 比如你已经定了叫ABC  那你就一直叫ABC  其他地方就不要使用ABC了
  timeout: 10
  keepalive: 20
  focusEventTopic: /Focus_Life/focusEvent           #任务完成后发送的topic
  addWaterTopic: /Focus_Life/addWater               #喝水一次后发送的topic
  getFocusOnTemplate: /Focus_Life/getTemplate       #主动获取任务模板的topic
  getWaterTopic: /Focus_Life/getWater               #主动获取今日喝水情况的topic
  sendTemplateTopic: /Focus_Life/sendTemplate/      #接收任务模板情况的topic
  sendWaterTopic: /Focus_Life/sendWater/            #接收今日喝水情况的topic
  weatherTopic: /Focus_Life/weather                 #接收天气情况的topic